spring:
  datasource:
    url: jdbc:mysql://120.78.226.71:3306/demo_vue?characterEncoding=utf8
    username: root
    password: suyukai
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: redis
  redis:
    database: 10
    host: 120.78.226.71
    port: 6379
    password: suyukai
    jedis:
      pool:
        max-idle: 300
        max-wait: 3000


mybatis:
  type-aliases-package: com.bosssoft.hr.train.springcloud.userclient.pojo

#测试bus-refresh刷新
getNullReturnMsg: "no such user"
